pr:
- master

jobs:
  - job: Verify_Build_and_Test
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: ./build-and-test-template.yml

    - task: ComponentGovernanceComponentDetection@0
      inputs:
        scanType: 'LogOnly'
        verbosity: 'Normal'
        alertWarningLevel: 'High'
        failOnAlert: true
