trigger: none

stages:
  - stage: 'build'
    displayName: 'Build and Test'
    pool:
      vmImage: 'ubuntu-16.04'
    jobs:
    - job: build_and_test
      displayName: 'Build and Test Source'
      steps:
      - template: .\build-and-test-template.yml
    - job: scan
      pool:
        vmImage: 'vs2017-win2016'
      steps:
      - task: ea576cd4-c61f-48f8-97e7-a3cb07b90a6f@2
        displayName: 'CredScan'
        inputs:
          scanFolder: '$(Build.SourcesDirectory)'
          outputFormat: sarif

  - stage: 'package'
    displayName: 'Package for all platforms'
    dependsOn: 'build'
    jobs:
    - job: packageWindows
      displayName: "Package for Windows"

      pool:
        vmImage: 'vs2017-win2016'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
          
      - template: '.\build-windows.yml'

      - task: CopyFiles@2
        displayName: 'ArtifactIgnore'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/'
          Contents: '.artifactignore'
          TargetFolder: '$(Build.SourcesDirectory)/dist/'

      - publish: $(Build.SourcesDirectory)/dist/
        displayName: 'Staging artifact for signing'
        artifact: Windows

    - job: packageMac
      displayName: "Package for MacOS"

      pool:
        vmImage: 'macOS-10.14'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
          
      - template: '.\build-mac.yml'

      - task: CopyFiles@2
        displayName: 'ArtifactIgnore'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/'
          Contents: '.artifactignore'
          TargetFolder: '$(Build.SourcesDirectory)/dist/'

      - publish: $(Build.SourcesDirectory)/dist/
        displayName: 'Staging artifact for signing'
        artifact: Mac

    - job: packageLinux
      displayName: "Package for Linux"
      pool:
          vmImage: 'ubuntu-16.04'

      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '12.x'
            
        - template: '.\build-linux.yml'

        - task: CopyFiles@2
          displayName: 'ArtifactIgnore'
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)/'
            Contents: '.artifactignore'
            TargetFolder: '$(Build.SourcesDirectory)/dist/'

        - publish: $(Build.SourcesDirectory)/dist/
          displayName: 'Staging artifact for signing'
          artifact: Linux

  - stage: 'codeSign'
    displayName: 'CodeSign and Release'
    dependsOn: 'package'
    pool:
      vmImage: 'ubuntu-16.04'
    jobs:

    - job: signWindows
      displayName: 'Windows'
      steps:
      - download: current
        artifact: Windows
      
      - task: EsrpCodeSigning@1
        displayName: 'Sign Windows MSI package'
        inputs:
          ConnectedServiceName: 'Azure IoT Explorer CodeSign'
          FolderPath: '$(Pipeline.Workspace)'
          Pattern: '*.msi'
          signConfigType: 'inlineSignParams'
          inlineOperation: |
            [
              {
                "KeyCode": "CP-230012",
                "OperationCode": "SigntoolSign",
                "Parameters": {
                  "OpusName": "Microsoft",
                  "OpusInfo": "http://www.microsoft.com",
                  "FileDigest": "/fd \"SHA256\"",
                  "PageHash": "/NPH",
                  "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                },
                "ToolName": "sign",
                "ToolVersion": "1.0"
              },
              {
                "KeyCode": "CP-230012",
                "OperationCode": "SigntoolVerify",
                "Parameters": {
                  "VerifyAll": "/all"
                },
                "ToolName": "sign",
                "ToolVersion": "1.0"
              }
            ]
          SessionTimeout: '60'
          MaxConcurrency: '50'
          MaxRetryAttempts: '5'
          VerboseLogin: false
      
      - task: CopyFiles@2
        displayName: 'ArtifactIgnore'
        inputs:
          SourceFolder: $(Build.SourcesDirectory)/
          Contents: '.artifactignore'
          TargetFolder: $(Pipeline.Workspace)

      - publish: $(Pipeline.Workspace)
        displayName: 'Staging signed artifact for release'
        artifact: Windows_Signed
        
    - job: signMac
      displayName: 'MacOS'
      steps:
      - download: current
        artifact: Mac

      - task: EsrpCodeSigning@1
        displayName: 'Sign MacOS DMG'
        inputs:
          ConnectedServiceName: 'Azure IoT Explorer CodeSign'
          FolderPath: '$(Pipeline.Workspace)'
          Pattern: '*.dmg'
          signConfigType: 'inlineSignParams'
          inlineOperation: |
            [
                {
                  "KeyCode" : "CP-401337-Apple",
                  "OperationCode" : "MacAppDeveloperSign",
                  "Parameters" : {},
                  "ToolName" : "sign",
                  "ToolVersion" : "1.0"
                }
            ]
          SessionTimeout: '60'
          MaxConcurrency: '50'
          MaxRetryAttempts: '5'
          VerboseLogin: false

      # - task: EsrpCodeSigning@1
      #   displayName: 'Sign MacOS DMG - Notarized'
      #   inputs:
      #     ConnectedServiceName: 'Azure IoT Explorer CodeSign'
      #     FolderPath: '$(Pipeline.Workspace)'
      #     Pattern: '*.dmg'
      #     signConfigType: 'inlineSignParams'
      #     inlineOperation: |
      #       [
      #         {
      #           "KeyCode" : "CP-401337-Apple",
      #           "OperationCode" : "MacAppNotarize",
      #           "Parameters" : {"BundleId":"com.microsoft.Azure.IoTExplorer"},
      #           "ToolName" : "sign",
      #           "ToolVersion" : "1.0"
      #         }
      #       ]
      #     SessionTimeout: '60'
      #     MaxConcurrency: '50'
      #     MaxRetryAttempts: '5'
      #     VerboseLogin: false
    
      - task: CopyFiles@2
        displayName: 'ArtifactIgnore'
        inputs:
          SourceFolder: $(Build.SourcesDirectory)/
          Contents: '.artifactignore'
          TargetFolder: $(Pipeline.Workspace)

      - publish: $(Pipeline.Workspace)
        displayName: 'Staging signed artifact for release'
        artifact: Mac_Signed

    - job: signLinux
      displayName: 'Linux'
      steps:
      - download: current
        artifact: Linux

      - task: EsrpCodeSigning@1
        displayName: 'Sign Linux DEB package'
        inputs:
          ConnectedServiceName: 'Azure IoT Explorer CodeSign'
          FolderPath: '$(Pipeline.Workspace)'
          Pattern: '*.deb'
          signConfigType: 'inlineSignParams'
          inlineOperation: |
            [
              {
                "KeyCode" : "CP-450778-Pgp",
                "OperationCode" : "LinuxSign",
                "Parameters" : {},
                "ToolName" : "sign",
                "ToolVersion" : "1.0"
              }
            ]
          SessionTimeout: '60'
          MaxConcurrency: '50'
          MaxRetryAttempts: '5'
          VerboseLogin: false

      - task: CopyFiles@2
        displayName: 'ArtifactIgnore'
        inputs:
          SourceFolder: $(Build.SourcesDirectory)/
          Contents: '.artifactignore'
          TargetFolder: $(Pipeline.Workspace)
      
      - publish: $(Pipeline.Workspace)
        displayName: 'Staging signed artifact for release'
        artifact: Linux_Signed

    - job: publishRelease
      displayName: 'Publish artifacts and draft GitHub Release'
      dependsOn:
      - signWindows
      - signMac
      - signLinux
      steps:
      - download: current
        artifact: Windows_Signed

      - download: current
        artifact: Mac_Signed
        
      - download: current
        artifact: Linux_Signed

      - task: CopyFiles@2
        displayName: 'Flatten files for release'
        inputs:
          SourceFolder: $(Pipeline.Workspace)
          Contents: |
            **/*.deb
            **/*.msi
            **/*.dmg
          flattenFolders: true
          TargetFolder: $(Pipeline.Workspace)/release

      - task: GitHubRelease@1
        displayName: 'Draft Github release (if tagged)'
        inputs:
          gitHubConnection: 'Azure IoT Explorer Github Service Connection'
          repositoryName: '$(Build.Repository.Name)'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'gitTag'
          isDraft: true
          addChangeLog: true
          assetUploadMode: replace
          changeLogCompareToRelease: 'lastFullRelease'
          changeLogType: 'commitBased'
          assets: '$(Pipeline.Workspace)/release/*.*'