//// This code is generated by a tool
/* tslint:disable */
export class ResourceKeys {
    public static breadcrumb = {
      addDevice : "breadcrumb.addDevice",
      devices : "breadcrumb.devices",
      hub : "breadcrumb.hub",
   };
   public static cloudToDeviceMessage = {
      addTimestamp : "cloudToDeviceMessage.addTimestamp",
      body : "cloudToDeviceMessage.body",
      bodyTooltip : "cloudToDeviceMessage.bodyTooltip",
      headerText : "cloudToDeviceMessage.headerText",
      output : "cloudToDeviceMessage.output",
      properties : {
         addCustomProperty : "cloudToDeviceMessage.properties.addCustomProperty",
         addSystemProperty : "cloudToDeviceMessage.properties.addSystemProperty",
         delete : "cloudToDeviceMessage.properties.delete",
         key : "cloudToDeviceMessage.properties.key",
         keyDup : "cloudToDeviceMessage.properties.keyDup",
         label : "cloudToDeviceMessage.properties.label",
         rowCheckBoxAriaLabel : "cloudToDeviceMessage.properties.rowCheckBoxAriaLabel",
         selectAllCheckboxAriaLabel : "cloudToDeviceMessage.properties.selectAllCheckboxAriaLabel",
         systemProperties : {
            ack : {
               description : "cloudToDeviceMessage.properties.systemProperties.ack.description",
               displayName : "cloudToDeviceMessage.properties.systemProperties.ack.displayName",
               full : "cloudToDeviceMessage.properties.systemProperties.ack.full",
               negative : "cloudToDeviceMessage.properties.systemProperties.ack.negative",
               positive : "cloudToDeviceMessage.properties.systemProperties.ack.positive",
            },
            contentEncoding : {
               description : "cloudToDeviceMessage.properties.systemProperties.contentEncoding.description",
               displayName : "cloudToDeviceMessage.properties.systemProperties.contentEncoding.displayName",
               utf16 : "cloudToDeviceMessage.properties.systemProperties.contentEncoding.utf16",
               utf32 : "cloudToDeviceMessage.properties.systemProperties.contentEncoding.utf32",
               utf8 : "cloudToDeviceMessage.properties.systemProperties.contentEncoding.utf8",
            },
            contentType : {
               description : "cloudToDeviceMessage.properties.systemProperties.contentType.description",
               displayName : "cloudToDeviceMessage.properties.systemProperties.contentType.displayName",
            },
            correlationId : {
               description : "cloudToDeviceMessage.properties.systemProperties.correlationId.description",
               displayName : "cloudToDeviceMessage.properties.systemProperties.correlationId.displayName",
            },
            expiryTimeUtc : {
               description : "cloudToDeviceMessage.properties.systemProperties.expiryTimeUtc.description",
               displayName : "cloudToDeviceMessage.properties.systemProperties.expiryTimeUtc.displayName",
               error : "cloudToDeviceMessage.properties.systemProperties.expiryTimeUtc.error",
            },
            lockToken : {
               description : "cloudToDeviceMessage.properties.systemProperties.lockToken.description",
               displayName : "cloudToDeviceMessage.properties.systemProperties.lockToken.displayName",
            },
            messageId : {
               description : "cloudToDeviceMessage.properties.systemProperties.messageId.description",
               displayName : "cloudToDeviceMessage.properties.systemProperties.messageId.displayName",
            },
         },
         toggleSelectionColumnAriaLabel : "cloudToDeviceMessage.properties.toggleSelectionColumnAriaLabel",
         tooltip : "cloudToDeviceMessage.properties.tooltip",
         value : "cloudToDeviceMessage.properties.value",
      },
      sendMessageButtonText : "cloudToDeviceMessage.sendMessageButtonText",
   };
   public static collapsibleSection = {
      close : "collapsibleSection.close",
      open : "collapsibleSection.open",
   };
   public static common = {
      close : "common.close",
      confirmationDialog : {
         no : "common.confirmationDialog.no",
         title : "common.confirmationDialog.title",
         yes : "common.confirmationDialog.yes",
      },
      learnMore : "common.learnMore",
      loading : "common.loading",
      maskedCopyableTextField : {
         copy : {
            label : "common.maskedCopyableTextField.copy.label",
         },
         toggleMask : {
            label : {
               hide : "common.maskedCopyableTextField.toggleMask.label.hide",
               show : "common.maskedCopyableTextField.toggleMask.label.show",
            },
         },
      },
   };
   public static connectivityPane = {
      connectionStringCheckbox : {
         ariaLabel : "connectivityPane.connectionStringCheckbox.ariaLabel",
         label : "connectivityPane.connectionStringCheckbox.label",
         tooltip : "connectivityPane.connectionStringCheckbox.tooltip",
      },
      connectionStringTextBox : {
         errorMessages : {
            invalid : "connectivityPane.connectionStringTextBox.errorMessages.invalid",
            required : "connectivityPane.connectionStringTextBox.errorMessages.required",
         },
         label : "connectivityPane.connectionStringTextBox.label",
         subLabel : "connectivityPane.connectionStringTextBox.subLabel",
      },
      dropDown : {
         copyButton : "connectivityPane.dropDown.copyButton",
         newEntry : "connectivityPane.dropDown.newEntry",
      },
      header : "connectivityPane.header",
      notes : "connectivityPane.notes",
      saveButton : {
         label : "connectivityPane.saveButton.label",
      },
   };
   public static deviceCommands = {
      columns : {
         name : "deviceCommands.columns.name",
         schema : {
            request : "deviceCommands.columns.schema.request",
            response : "deviceCommands.columns.schema.response",
         },
         type : "deviceCommands.columns.type",
      },
      command : {
         collapse : "deviceCommands.command.collapse",
         collapseAll : "deviceCommands.command.collapseAll",
         expand : "deviceCommands.command.expand",
         expandAll : "deviceCommands.command.expandAll",
         refresh : "deviceCommands.command.refresh",
         submit : "deviceCommands.command.submit",
      },
      headerText : "deviceCommands.headerText",
      noCommands : "deviceCommands.noCommands",
   };
   public static deviceContent = {
      navBar : {
         add : "deviceContent.navBar.add",
         addModuleIdentity : "deviceContent.navBar.addModuleIdentity",
         cloudToDeviceMessage : "deviceContent.navBar.cloudToDeviceMessage",
         collapse : "deviceContent.navBar.collapse",
         commands : "deviceContent.navBar.commands",
         events : "deviceContent.navBar.events",
         eventsPerInterface : "deviceContent.navBar.eventsPerInterface",
         expand : "deviceContent.navBar.expand",
         identity : "deviceContent.navBar.identity",
         interfaces : "deviceContent.navBar.interfaces",
         methods : "deviceContent.navBar.methods",
         moduleIdentity : "deviceContent.navBar.moduleIdentity",
         nonpnp : "deviceContent.navBar.nonpnp",
         pnp : "deviceContent.navBar.pnp",
         properties : "deviceContent.navBar.properties",
         settings : "deviceContent.navBar.settings",
         twin : "deviceContent.navBar.twin",
      },
      start : "deviceContent.start",
      value : "deviceContent.value",
   };
   public static deviceEvents = {
      columns : {
         displayName : "deviceEvents.columns.displayName",
         error : {
            key : {
               errorContent : "deviceEvents.columns.error.key.errorContent",
               label : "deviceEvents.columns.error.key.label",
            },
            value : {
               label : "deviceEvents.columns.error.value.label",
            },
         },
         schema : "deviceEvents.columns.schema",
         timestamp : "deviceEvents.columns.timestamp",
         unit : "deviceEvents.columns.unit",
         value : "deviceEvents.columns.value",
      },
      command : {
         clearEvents : "deviceEvents.command.clearEvents",
         refresh : "deviceEvents.command.refresh",
         showSystemProperties : "deviceEvents.command.showSystemProperties",
         start : "deviceEvents.command.start",
         stop : "deviceEvents.command.stop",
      },
      consumerGroups : {
         label : "deviceEvents.consumerGroups.label",
         tooltip : "deviceEvents.consumerGroups.tooltip",
      },
      event : {
         body : "deviceEvents.event.body",
         enqueuedTime : "deviceEvents.event.enqueuedTime",
         properties : "deviceEvents.event.properties",
      },
      headerText : "deviceEvents.headerText",
      infiniteScroll : {
         loading : "deviceEvents.infiniteScroll.loading",
      },
      interfaceDropDown : {
         label : "deviceEvents.interfaceDropDown.label",
         placeHolder : "deviceEvents.interfaceDropDown.placeHolder",
      },
   };
   public static deviceIdentity = {
      authenticationType : {
         ca : {
            text : "deviceIdentity.authenticationType.ca.text",
            type : "deviceIdentity.authenticationType.ca.type",
         },
         sasToken : {
            expiration : "deviceIdentity.authenticationType.sasToken.expiration",
            generateButton : {
               text : "deviceIdentity.authenticationType.sasToken.generateButton.text",
               title : "deviceIdentity.authenticationType.sasToken.generateButton.title",
            },
            label : "deviceIdentity.authenticationType.sasToken.label",
            symmetricKey : "deviceIdentity.authenticationType.sasToken.symmetricKey",
            textField : {
               ariaLabel : "deviceIdentity.authenticationType.sasToken.textField.ariaLabel",
               label : "deviceIdentity.authenticationType.sasToken.textField.label",
            },
            toolTip : "deviceIdentity.authenticationType.sasToken.toolTip",
         },
         selfSigned : {
            primaryThumbprint : "deviceIdentity.authenticationType.selfSigned.primaryThumbprint",
            primaryThumbprintTooltip : "deviceIdentity.authenticationType.selfSigned.primaryThumbprintTooltip",
            secondaryThumbprint : "deviceIdentity.authenticationType.selfSigned.secondaryThumbprint",
            secondaryThumbprintTooltip : "deviceIdentity.authenticationType.selfSigned.secondaryThumbprintTooltip",
            text : "deviceIdentity.authenticationType.selfSigned.text",
            type : "deviceIdentity.authenticationType.selfSigned.type",
         },
         symmetricKey : {
            autoGenerate : "deviceIdentity.authenticationType.symmetricKey.autoGenerate",
            generatePrimaryKey : "deviceIdentity.authenticationType.symmetricKey.generatePrimaryKey",
            generateSecondaryKey : "deviceIdentity.authenticationType.symmetricKey.generateSecondaryKey",
            primaryConnectionString : "deviceIdentity.authenticationType.symmetricKey.primaryConnectionString",
            primaryConnectionStringTooltip : "deviceIdentity.authenticationType.symmetricKey.primaryConnectionStringTooltip",
            primaryKey : "deviceIdentity.authenticationType.symmetricKey.primaryKey",
            secondaryConnectionString : "deviceIdentity.authenticationType.symmetricKey.secondaryConnectionString",
            secondaryConnectionStringTooltip : "deviceIdentity.authenticationType.symmetricKey.secondaryConnectionStringTooltip",
            secondaryKey : "deviceIdentity.authenticationType.symmetricKey.secondaryKey",
            type : "deviceIdentity.authenticationType.symmetricKey.type",
         },
         text : "deviceIdentity.authenticationType.text",
      },
      commands : {
         manageKeys : {
            ariaLabel : "deviceIdentity.commands.manageKeys.ariaLabel",
            label : "deviceIdentity.commands.manageKeys.label",
         },
         regeneratePrimary : {
            ariaLabel : "deviceIdentity.commands.regeneratePrimary.ariaLabel",
            label : "deviceIdentity.commands.regeneratePrimary.label",
         },
         regenerateSecondary : {
            ariaLabel : "deviceIdentity.commands.regenerateSecondary.ariaLabel",
            label : "deviceIdentity.commands.regenerateSecondary.label",
         },
         save : "deviceIdentity.commands.save",
         swapKeys : {
            ariaLabel : "deviceIdentity.commands.swapKeys.ariaLabel",
            label : "deviceIdentity.commands.swapKeys.label",
         },
      },
      deviceID : "deviceIdentity.deviceID",
      deviceIDTooltip : "deviceIdentity.deviceIDTooltip",
      headerText : "deviceIdentity.headerText",
      hubConnectivity : {
         disable : "deviceIdentity.hubConnectivity.disable",
         disabled : "deviceIdentity.hubConnectivity.disabled",
         enable : "deviceIdentity.hubConnectivity.enable",
         enabled : "deviceIdentity.hubConnectivity.enabled",
         label : "deviceIdentity.hubConnectivity.label",
         tooltip : "deviceIdentity.hubConnectivity.tooltip",
      },
      validation : {
         invalidDeviceId : "deviceIdentity.validation.invalidDeviceId",
         invalidKey : "deviceIdentity.validation.invalidKey",
         invalidThumbprint : "deviceIdentity.validation.invalidThumbprint",
      },
   };
   public static deviceInterfaces = {
      columns : {
         description : "deviceInterfaces.columns.description",
         displayName : "deviceInterfaces.columns.displayName",
         noSource : "deviceInterfaces.columns.noSource",
         source : "deviceInterfaces.columns.source",
      },
      command : {
         configure : "deviceInterfaces.command.configure",
         refresh : "deviceInterfaces.command.refresh",
      },
      headerText : "deviceInterfaces.headerText",
      interfaceNotFound : "deviceInterfaces.interfaceNotFound",
      noInterfaces : "deviceInterfaces.noInterfaces",
   };
   public static deviceLists = {
      columns : {
         authenticationType : "deviceLists.columns.authenticationType",
         cloudToDeviceMessageCount : "deviceLists.columns.cloudToDeviceMessageCount",
         connection : "deviceLists.columns.connection",
         deviceId : {
            infoText : "deviceLists.columns.deviceId.infoText",
            label : "deviceLists.columns.deviceId.label",
         },
         interfaces : "deviceLists.columns.interfaces",
         isEdgeDevice : {
            label : "deviceLists.columns.isEdgeDevice.label",
            no : "deviceLists.columns.isEdgeDevice.no",
            yes : "deviceLists.columns.isEdgeDevice.yes",
         },
         isPnpDevice : "deviceLists.columns.isPnpDevice",
         lastActivityTime : "deviceLists.columns.lastActivityTime",
         status : {
            infoText : "deviceLists.columns.status.infoText",
            label : "deviceLists.columns.status.label",
         },
         statusUpdatedTime : "deviceLists.columns.statusUpdatedTime",
      },
      commands : {
         add : "deviceLists.commands.add",
         close : "deviceLists.commands.close",
         delete : {
            buttonText : "deviceLists.commands.delete.buttonText",
            confirmationDialog : {
               cancel : "deviceLists.commands.delete.confirmationDialog.cancel",
               confirm : "deviceLists.commands.delete.confirmationDialog.confirm",
               subText : "deviceLists.commands.delete.confirmationDialog.subText",
               title : "deviceLists.commands.delete.confirmationDialog.title",
            },
         },
         refresh : "deviceLists.commands.refresh",
         save : "deviceLists.commands.save",
      },
      loadingDevice : "deviceLists.loadingDevice",
      messageBar : {
         link : "deviceLists.messageBar.link",
         message : "deviceLists.messageBar.message",
      },
      noData : "deviceLists.noData",
      noDevice : "deviceLists.noDevice",
      paging : {
         pages : "deviceLists.paging.pages",
      },
      query : {
         deviceId : {
            ariaLabel : "deviceLists.query.deviceId.ariaLabel",
            placeholder : "deviceLists.query.deviceId.placeholder",
            searchButton : {
               ariaLabel : "deviceLists.query.deviceId.searchButton.ariaLabel",
               title : "deviceLists.query.deviceId.searchButton.title",
            },
         },
         searchPills : {
            add : {
               ariaLabel : "deviceLists.query.searchPills.add.ariaLabel",
               text : "deviceLists.query.searchPills.add.text",
               title : "deviceLists.query.searchPills.add.title",
            },
            clause : {
               operationType : {
                  ariaLabel : "deviceLists.query.searchPills.clause.operationType.ariaLabel",
                  options : {
                     equals : "deviceLists.query.searchPills.clause.operationType.options.equals",
                     notEquals : "deviceLists.query.searchPills.clause.operationType.options.notEquals",
                  },
                  title : "deviceLists.query.searchPills.clause.operationType.title",
               },
               parameterType : {
                  ariaLabel : "deviceLists.query.searchPills.clause.parameterType.ariaLabel",
                  items : {
                     capabilityModelId : "deviceLists.query.searchPills.clause.parameterType.items.capabilityModelId",
                     edge : "deviceLists.query.searchPills.clause.parameterType.items.edge",
                     interfaceId : "deviceLists.query.searchPills.clause.parameterType.items.interfaceId",
                     lastActivityTime : "deviceLists.query.searchPills.clause.parameterType.items.lastActivityTime",
                     propertyValue : "deviceLists.query.searchPills.clause.parameterType.items.propertyValue",
                     status : "deviceLists.query.searchPills.clause.parameterType.items.status",
                     statusUpdateTime : "deviceLists.query.searchPills.clause.parameterType.items.statusUpdateTime",
                  },
                  title : "deviceLists.query.searchPills.clause.parameterType.title",
               },
               remove : {
                  ariaLabel : "deviceLists.query.searchPills.clause.remove.ariaLabel",
                  title : "deviceLists.query.searchPills.clause.remove.title",
               },
               value : {
                  ariaLabel : "deviceLists.query.searchPills.clause.value.ariaLabel",
                  deviceCapability : {
                     edge : "deviceLists.query.searchPills.clause.value.deviceCapability.edge",
                     nonEdge : "deviceLists.query.searchPills.clause.value.deviceCapability.nonEdge",
                  },
                  deviceStatus : {
                     disabled : "deviceLists.query.searchPills.clause.value.deviceStatus.disabled",
                     enabled : "deviceLists.query.searchPills.clause.value.deviceStatus.enabled",
                  },
                  placeholder : "deviceLists.query.searchPills.clause.value.placeholder",
                  title : "deviceLists.query.searchPills.clause.value.title",
               },
            },
            search : {
               ariaLabel : "deviceLists.query.searchPills.search.ariaLabel",
               text : "deviceLists.query.searchPills.search.text",
               title : "deviceLists.query.searchPills.search.title",
            },
         },
      },
   };
   public static deviceProperties = {
      columns : {
         error : "deviceProperties.columns.error",
         name : "deviceProperties.columns.name",
         schema : "deviceProperties.columns.schema",
         unit : "deviceProperties.columns.unit",
         value : "deviceProperties.columns.value",
      },
      command : {
         openReportedValuePanel : "deviceProperties.command.openReportedValuePanel",
         refresh : "deviceProperties.command.refresh",
      },
      editor : {
         label : "deviceProperties.editor.label",
      },
      headerText : "deviceProperties.headerText",
      noProperty : "deviceProperties.noProperty",
   };
   public static deviceSettings = {
      columns : {
         error : "deviceSettings.columns.error",
         name : "deviceSettings.columns.name",
         reportedValue : "deviceSettings.columns.reportedValue",
         reportedValueTooltip : "deviceSettings.columns.reportedValueTooltip",
         schema : "deviceSettings.columns.schema",
         unit : "deviceSettings.columns.unit",
      },
      command : {
         collapse : "deviceSettings.command.collapse",
         collapseAll : "deviceSettings.command.collapseAll",
         expand : "deviceSettings.command.expand",
         expandAll : "deviceSettings.command.expandAll",
         openDesiredValuePanel : "deviceSettings.command.openDesiredValuePanel",
         openReportedValuePanel : "deviceSettings.command.openReportedValuePanel",
         refresh : "deviceSettings.command.refresh",
         submit : "deviceSettings.command.submit",
      },
      desiredState : {
         error : "deviceSettings.desiredState.error",
         success : "deviceSettings.desiredState.success",
         synching : "deviceSettings.desiredState.synching",
         unknown : "deviceSettings.desiredState.unknown",
      },
      headerText : "deviceSettings.headerText",
      noSetting : "deviceSettings.noSetting",
      panel : {
         title : "deviceSettings.panel.title",
      },
      previewPayloadButtonText : "deviceSettings.previewPayloadButtonText",
      syncStatus : {
         failed : "deviceSettings.syncStatus.failed",
         label : "deviceSettings.syncStatus.label",
         synced : "deviceSettings.syncStatus.synced",
         syncing : "deviceSettings.syncStatus.syncing",
      },
   };
   public static deviceTwin = {
      command : {
         refresh : "deviceTwin.command.refresh",
         save : "deviceTwin.command.save",
      },
      headerText : "deviceTwin.headerText",
      notFound : "deviceTwin.notFound",
   };
   public static directMethod = {
      connectionTimeout : "directMethod.connectionTimeout",
      connectionTimeoutTooltip : "directMethod.connectionTimeoutTooltip",
      headerText : "directMethod.headerText",
      invokeMethodButtonText : "directMethod.invokeMethodButtonText",
      methodName : "directMethod.methodName",
      methodNamePlaceHolder : "directMethod.methodNamePlaceHolder",
      payload : "directMethod.payload",
      payloadTooltip : "directMethod.payloadTooltip",
      responseTimeout : "directMethod.responseTimeout",
      responseTimeoutTooltip : "directMethod.responseTimeoutTooltip",
      result : "directMethod.result",
   };
   public static errorBoundary = {
      text : "errorBoundary.text",
   };
   public static header = {
      applicationName : "header.applicationName",
      notifications : {
         dismiss : "header.notifications.dismiss",
         hide : "header.notifications.hide",
         panel : {
            noNotifications : "header.notifications.panel.noNotifications",
            title : "header.notifications.panel.title",
         },
         show : "header.notifications.show",
      },
      questions : {
         launch : "header.questions.launch",
      },
      search : {
         watermark : "header.search.watermark",
      },
      settings : {
         launch : "header.settings.launch",
      },
   };
   public static moduleIdentity = {
      addModuleHeaderText : "moduleIdentity.addModuleHeaderText",
      authenticationType : {
         ca : {
            text : "moduleIdentity.authenticationType.ca.text",
            type : "moduleIdentity.authenticationType.ca.type",
         },
         selfSigned : {
            primaryThumbprint : "moduleIdentity.authenticationType.selfSigned.primaryThumbprint",
            primaryThumbprintTooltip : "moduleIdentity.authenticationType.selfSigned.primaryThumbprintTooltip",
            secondaryThumbprint : "moduleIdentity.authenticationType.selfSigned.secondaryThumbprint",
            secondaryThumbprintTooltip : "moduleIdentity.authenticationType.selfSigned.secondaryThumbprintTooltip",
            text : "moduleIdentity.authenticationType.selfSigned.text",
            type : "moduleIdentity.authenticationType.selfSigned.type",
         },
         symmetricKey : {
            autoGenerate : "moduleIdentity.authenticationType.symmetricKey.autoGenerate",
            generatePrimaryKey : "moduleIdentity.authenticationType.symmetricKey.generatePrimaryKey",
            generateSecondaryKey : "moduleIdentity.authenticationType.symmetricKey.generateSecondaryKey",
            primaryConnectionString : "moduleIdentity.authenticationType.symmetricKey.primaryConnectionString",
            primaryConnectionStringTooltip : "moduleIdentity.authenticationType.symmetricKey.primaryConnectionStringTooltip",
            primaryKey : "moduleIdentity.authenticationType.symmetricKey.primaryKey",
            secondaryConnectionString : "moduleIdentity.authenticationType.symmetricKey.secondaryConnectionString",
            secondaryConnectionStringTooltip : "moduleIdentity.authenticationType.symmetricKey.secondaryConnectionStringTooltip",
            secondaryKey : "moduleIdentity.authenticationType.symmetricKey.secondaryKey",
            type : "moduleIdentity.authenticationType.symmetricKey.type",
         },
         text : "moduleIdentity.authenticationType.text",
      },
      columns : {
         connectionState : "moduleIdentity.columns.connectionState",
         connectionStateLastUpdated : "moduleIdentity.columns.connectionStateLastUpdated",
         lastActivityTime : "moduleIdentity.columns.lastActivityTime",
         moduleId : "moduleIdentity.columns.moduleId",
      },
      command : {
         add : "moduleIdentity.command.add",
         cancel : "moduleIdentity.command.cancel",
         refresh : "moduleIdentity.command.refresh",
         save : "moduleIdentity.command.save",
      },
      errorFetching : "moduleIdentity.errorFetching",
      headerText : "moduleIdentity.headerText",
      moduleId : "moduleIdentity.moduleId",
      moduleIdTooltip : "moduleIdentity.moduleIdTooltip",
      noModules : "moduleIdentity.noModules",
      validation : {
         invalidKey : "moduleIdentity.validation.invalidKey",
         invalidModuleIdentityName : "moduleIdentity.validation.invalidModuleIdentityName",
         invalidThumbprint : "moduleIdentity.validation.invalidThumbprint",
      },
   };
   public static noMatchError = {
      description : "noMatchError.description",
      goHome : "noMatchError.goHome",
      title : "noMatchError.title",
   };
   public static notifications = {
      addDeviceOnError : "notifications.addDeviceOnError",
      addDeviceOnSucceed : "notifications.addDeviceOnSucceed",
      addModuleIdentityOnError : "notifications.addModuleIdentityOnError",
      addModuleIdentityOnSucceed : "notifications.addModuleIdentityOnSucceed",
      cloudToDeviceMessageOnError : "notifications.cloudToDeviceMessageOnError",
      cloudToDeviceMessageOnSuccess : "notifications.cloudToDeviceMessageOnSuccess",
      copiedToClipboard : "notifications.copiedToClipboard",
      deleteDeviceOnError : "notifications.deleteDeviceOnError",
      deleteDeviceOnSucceed : "notifications.deleteDeviceOnSucceed",
      getDeviceIdentityOnError : "notifications.getDeviceIdentityOnError",
      getDeviceListGenericErrorHelp : "notifications.getDeviceListGenericErrorHelp",
      getDeviceListOnError : "notifications.getDeviceListOnError",
      getDeviceListQueryGenericErrorHelp : "notifications.getDeviceListQueryGenericErrorHelp",
      getDeviceTwinOnError : "notifications.getDeviceTwinOnError",
      getDigitalTwinInterfacePropertiesOnError : "notifications.getDigitalTwinInterfacePropertiesOnError",
      getInterfaceModelOnError : "notifications.getInterfaceModelOnError",
      getModuleIdentitiesOnError : "notifications.getModuleIdentitiesOnError",
      interfaceSchemaNotSupported : "notifications.interfaceSchemaNotSupported",
      invokeDigitalTwinCommandOnError : "notifications.invokeDigitalTwinCommandOnError",
      invokeDigitalTwinCommandOnSuccess : "notifications.invokeDigitalTwinCommandOnSuccess",
      invokeMethodOnError : "notifications.invokeMethodOnError",
      invokeMethodOnSuccess : "notifications.invokeMethodOnSuccess",
      invokingDigitalTwinCommand : "notifications.invokingDigitalTwinCommand",
      invokingDigitalTwinCommandWithPayload : "notifications.invokingDigitalTwinCommandWithPayload",
      invokingMethod : "notifications.invokingMethod",
      invokingMethodWithPayload : "notifications.invokingMethodWithPayload",
      patchDigitalTwinInterfacePropertiesOnError : "notifications.patchDigitalTwinInterfacePropertiesOnError",
      patchDigitalTwinInterfacePropertiesOnSuccess : "notifications.patchDigitalTwinInterfacePropertiesOnSuccess",
      savedToIotHubConnectionString : "notifications.savedToIotHubConnectionString",
      sendingCloudToDeviceMessage : "notifications.sendingCloudToDeviceMessage",
      updateDeviceOnError : "notifications.updateDeviceOnError",
      updateDeviceOnSucceed : "notifications.updateDeviceOnSucceed",
      updateDeviceTwinOnError : "notifications.updateDeviceTwinOnError",
      updateDeviceTwinOnSuccess : "notifications.updateDeviceTwinOnSuccess",
   };
   public static settings = {
      cancel : "settings.cancel",
      configuration : {
         connectionString : {
            label : "settings.configuration.connectionString.label",
            link : "settings.configuration.connectionString.link",
            sublabel : "settings.configuration.connectionString.sublabel",
         },
         headerText : "settings.configuration.headerText",
      },
      confirmationMessage : "settings.confirmationMessage",
      footerText : "settings.footerText",
      headerText : "settings.headerText",
      logout : "settings.logout",
      modelDefinitions : {
         add : "settings.modelDefinitions.add",
         headerText : "settings.modelDefinitions.headerText",
         helpText : "settings.modelDefinitions.helpText",
         repositoryTypes : {
            device : {
               infoText : "settings.modelDefinitions.repositoryTypes.device.infoText",
               label : "settings.modelDefinitions.repositoryTypes.device.label",
            },
            private : {
               infoText : "settings.modelDefinitions.repositoryTypes.private.infoText",
               label : "settings.modelDefinitions.repositoryTypes.private.label",
               placeholder : "settings.modelDefinitions.repositoryTypes.private.placeholder",
               textBoxLabel : "settings.modelDefinitions.repositoryTypes.private.textBoxLabel",
            },
            public : {
               infoText : "settings.modelDefinitions.repositoryTypes.public.infoText",
               label : "settings.modelDefinitions.repositoryTypes.public.label",
            },
         },
      },
      questions : {
         headerText : "settings.questions.headerText",
         questions : {
            documentation : {
               link : "settings.questions.questions.documentation.link",
               text : "settings.questions.questions.documentation.text",
            },
         },
      },
      save : "settings.save",
      theme : {
         darkTheme : "settings.theme.darkTheme",
         headerText : "settings.theme.headerText",
         label : "settings.theme.label",
         lightTheme : "settings.theme.lightTheme",
      },
   };
   public static template = {
      array : {
         add : "template.array.add",
         remove : "template.array.remove",
      },
      collapse : {
         close : "template.collapse.close",
         open : "template.collapse.open",
      },
   };
}
/* tslint:enable */
