name: Node CI

on:
    pull_request:
        branches:
            - main
            - dev

jobs:
    build:

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [24.x]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
        - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        - name: Use Node ${{ matrix.node-version }}
          uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
          with:
              node-version: ${{ matrix.node-version }}
        - name: npm install, build, and test
          timeout-minutes: 25
          run: |
              npm ci --legacy-peer-deps
              npm run build --if-present
              npm test
