name: Node CI

on:
    pull_request:
        branches:
            - main
            - dev

jobs:
    build:

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [24.x]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        - name: Use Node ${{ matrix.node-version }}
          uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
          with:
              node-version: ${{ matrix.node-version }}
        - name: npm install, build, and test
          timeout-minutes: 25
          run: |
              npm ci --legacy-peer-deps
              npm run build --if-present
              npm test
